name: CI-LuaCheck

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1